// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Value.proto

public final class Value {
  private Value() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ValueInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 nbt = 1;
    /**
     * <code>required int64 nbt = 1;</code>
     */
    boolean hasNbt();
    /**
     * <code>required int64 nbt = 1;</code>
     */
    long getNbt();

    // repeated .EntryInfo imageSet = 2;
    /**
     * <code>repeated .EntryInfo imageSet = 2;</code>
     */
    java.util.List<Value.EntryInfo> 
        getImageSetList();
    /**
     * <code>repeated .EntryInfo imageSet = 2;</code>
     */
    Value.EntryInfo getImageSet(int index);
    /**
     * <code>repeated .EntryInfo imageSet = 2;</code>
     */
    int getImageSetCount();
    /**
     * <code>repeated .EntryInfo imageSet = 2;</code>
     */
    java.util.List<? extends Value.EntryInfoOrBuilder> 
        getImageSetOrBuilderList();
    /**
     * <code>repeated .EntryInfo imageSet = 2;</code>
     */
    Value.EntryInfoOrBuilder getImageSetOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ValueInfo}
   */
  public static final class ValueInfo extends
      com.google.protobuf.GeneratedMessage
      implements ValueInfoOrBuilder {
    // Use ValueInfo.newBuilder() to construct.
    private ValueInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ValueInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ValueInfo defaultInstance;
    public static ValueInfo getDefaultInstance() {
      return defaultInstance;
    }

    public ValueInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ValueInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              nbt_ = input.readInt64();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                imageSet_ = new java.util.ArrayList<Value.EntryInfo>();
                mutable_bitField0_ |= 0x00000002;
              }
              imageSet_.add(input.readMessage(Value.EntryInfo.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          imageSet_ = java.util.Collections.unmodifiableList(imageSet_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Value.internal_static_ValueInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Value.internal_static_ValueInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Value.ValueInfo.class, Value.ValueInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<ValueInfo> PARSER =
        new com.google.protobuf.AbstractParser<ValueInfo>() {
      public ValueInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ValueInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ValueInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 nbt = 1;
    public static final int NBT_FIELD_NUMBER = 1;
    private long nbt_;
    /**
     * <code>required int64 nbt = 1;</code>
     */
    public boolean hasNbt() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 nbt = 1;</code>
     */
    public long getNbt() {
      return nbt_;
    }

    // repeated .EntryInfo imageSet = 2;
    public static final int IMAGESET_FIELD_NUMBER = 2;
    private java.util.List<Value.EntryInfo> imageSet_;
    /**
     * <code>repeated .EntryInfo imageSet = 2;</code>
     */
    public java.util.List<Value.EntryInfo> getImageSetList() {
      return imageSet_;
    }
    /**
     * <code>repeated .EntryInfo imageSet = 2;</code>
     */
    public java.util.List<? extends Value.EntryInfoOrBuilder> 
        getImageSetOrBuilderList() {
      return imageSet_;
    }
    /**
     * <code>repeated .EntryInfo imageSet = 2;</code>
     */
    public int getImageSetCount() {
      return imageSet_.size();
    }
    /**
     * <code>repeated .EntryInfo imageSet = 2;</code>
     */
    public Value.EntryInfo getImageSet(int index) {
      return imageSet_.get(index);
    }
    /**
     * <code>repeated .EntryInfo imageSet = 2;</code>
     */
    public Value.EntryInfoOrBuilder getImageSetOrBuilder(
        int index) {
      return imageSet_.get(index);
    }

    private void initFields() {
      nbt_ = 0L;
      imageSet_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasNbt()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getImageSetCount(); i++) {
        if (!getImageSet(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, nbt_);
      }
      for (int i = 0; i < imageSet_.size(); i++) {
        output.writeMessage(2, imageSet_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, nbt_);
      }
      for (int i = 0; i < imageSet_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, imageSet_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Value.ValueInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Value.ValueInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Value.ValueInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Value.ValueInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Value.ValueInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Value.ValueInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Value.ValueInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Value.ValueInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Value.ValueInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Value.ValueInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Value.ValueInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ValueInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Value.ValueInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Value.internal_static_ValueInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Value.internal_static_ValueInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Value.ValueInfo.class, Value.ValueInfo.Builder.class);
      }

      // Construct using Value.ValueInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getImageSetFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        nbt_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (imageSetBuilder_ == null) {
          imageSet_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          imageSetBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Value.internal_static_ValueInfo_descriptor;
      }

      public Value.ValueInfo getDefaultInstanceForType() {
        return Value.ValueInfo.getDefaultInstance();
      }

      public Value.ValueInfo build() {
        Value.ValueInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Value.ValueInfo buildPartial() {
        Value.ValueInfo result = new Value.ValueInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.nbt_ = nbt_;
        if (imageSetBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            imageSet_ = java.util.Collections.unmodifiableList(imageSet_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.imageSet_ = imageSet_;
        } else {
          result.imageSet_ = imageSetBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Value.ValueInfo) {
          return mergeFrom((Value.ValueInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Value.ValueInfo other) {
        if (other == Value.ValueInfo.getDefaultInstance()) return this;
        if (other.hasNbt()) {
          setNbt(other.getNbt());
        }
        if (imageSetBuilder_ == null) {
          if (!other.imageSet_.isEmpty()) {
            if (imageSet_.isEmpty()) {
              imageSet_ = other.imageSet_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureImageSetIsMutable();
              imageSet_.addAll(other.imageSet_);
            }
            onChanged();
          }
        } else {
          if (!other.imageSet_.isEmpty()) {
            if (imageSetBuilder_.isEmpty()) {
              imageSetBuilder_.dispose();
              imageSetBuilder_ = null;
              imageSet_ = other.imageSet_;
              bitField0_ = (bitField0_ & ~0x00000002);
              imageSetBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getImageSetFieldBuilder() : null;
            } else {
              imageSetBuilder_.addAllMessages(other.imageSet_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasNbt()) {
          
          return false;
        }
        for (int i = 0; i < getImageSetCount(); i++) {
          if (!getImageSet(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Value.ValueInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Value.ValueInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 nbt = 1;
      private long nbt_ ;
      /**
       * <code>required int64 nbt = 1;</code>
       */
      public boolean hasNbt() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 nbt = 1;</code>
       */
      public long getNbt() {
        return nbt_;
      }
      /**
       * <code>required int64 nbt = 1;</code>
       */
      public Builder setNbt(long value) {
        bitField0_ |= 0x00000001;
        nbt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 nbt = 1;</code>
       */
      public Builder clearNbt() {
        bitField0_ = (bitField0_ & ~0x00000001);
        nbt_ = 0L;
        onChanged();
        return this;
      }

      // repeated .EntryInfo imageSet = 2;
      private java.util.List<Value.EntryInfo> imageSet_ =
        java.util.Collections.emptyList();
      private void ensureImageSetIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          imageSet_ = new java.util.ArrayList<Value.EntryInfo>(imageSet_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          Value.EntryInfo, Value.EntryInfo.Builder, Value.EntryInfoOrBuilder> imageSetBuilder_;

      /**
       * <code>repeated .EntryInfo imageSet = 2;</code>
       */
      public java.util.List<Value.EntryInfo> getImageSetList() {
        if (imageSetBuilder_ == null) {
          return java.util.Collections.unmodifiableList(imageSet_);
        } else {
          return imageSetBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .EntryInfo imageSet = 2;</code>
       */
      public int getImageSetCount() {
        if (imageSetBuilder_ == null) {
          return imageSet_.size();
        } else {
          return imageSetBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .EntryInfo imageSet = 2;</code>
       */
      public Value.EntryInfo getImageSet(int index) {
        if (imageSetBuilder_ == null) {
          return imageSet_.get(index);
        } else {
          return imageSetBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .EntryInfo imageSet = 2;</code>
       */
      public Builder setImageSet(
          int index, Value.EntryInfo value) {
        if (imageSetBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureImageSetIsMutable();
          imageSet_.set(index, value);
          onChanged();
        } else {
          imageSetBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .EntryInfo imageSet = 2;</code>
       */
      public Builder setImageSet(
          int index, Value.EntryInfo.Builder builderForValue) {
        if (imageSetBuilder_ == null) {
          ensureImageSetIsMutable();
          imageSet_.set(index, builderForValue.build());
          onChanged();
        } else {
          imageSetBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .EntryInfo imageSet = 2;</code>
       */
      public Builder addImageSet(Value.EntryInfo value) {
        if (imageSetBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureImageSetIsMutable();
          imageSet_.add(value);
          onChanged();
        } else {
          imageSetBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .EntryInfo imageSet = 2;</code>
       */
      public Builder addImageSet(
          int index, Value.EntryInfo value) {
        if (imageSetBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureImageSetIsMutable();
          imageSet_.add(index, value);
          onChanged();
        } else {
          imageSetBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .EntryInfo imageSet = 2;</code>
       */
      public Builder addImageSet(
          Value.EntryInfo.Builder builderForValue) {
        if (imageSetBuilder_ == null) {
          ensureImageSetIsMutable();
          imageSet_.add(builderForValue.build());
          onChanged();
        } else {
          imageSetBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .EntryInfo imageSet = 2;</code>
       */
      public Builder addImageSet(
          int index, Value.EntryInfo.Builder builderForValue) {
        if (imageSetBuilder_ == null) {
          ensureImageSetIsMutable();
          imageSet_.add(index, builderForValue.build());
          onChanged();
        } else {
          imageSetBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .EntryInfo imageSet = 2;</code>
       */
      public Builder addAllImageSet(
          java.lang.Iterable<? extends Value.EntryInfo> values) {
        if (imageSetBuilder_ == null) {
          ensureImageSetIsMutable();
          super.addAll(values, imageSet_);
          onChanged();
        } else {
          imageSetBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .EntryInfo imageSet = 2;</code>
       */
      public Builder clearImageSet() {
        if (imageSetBuilder_ == null) {
          imageSet_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          imageSetBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .EntryInfo imageSet = 2;</code>
       */
      public Builder removeImageSet(int index) {
        if (imageSetBuilder_ == null) {
          ensureImageSetIsMutable();
          imageSet_.remove(index);
          onChanged();
        } else {
          imageSetBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .EntryInfo imageSet = 2;</code>
       */
      public Value.EntryInfo.Builder getImageSetBuilder(
          int index) {
        return getImageSetFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .EntryInfo imageSet = 2;</code>
       */
      public Value.EntryInfoOrBuilder getImageSetOrBuilder(
          int index) {
        if (imageSetBuilder_ == null) {
          return imageSet_.get(index);  } else {
          return imageSetBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .EntryInfo imageSet = 2;</code>
       */
      public java.util.List<? extends Value.EntryInfoOrBuilder> 
           getImageSetOrBuilderList() {
        if (imageSetBuilder_ != null) {
          return imageSetBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(imageSet_);
        }
      }
      /**
       * <code>repeated .EntryInfo imageSet = 2;</code>
       */
      public Value.EntryInfo.Builder addImageSetBuilder() {
        return getImageSetFieldBuilder().addBuilder(
            Value.EntryInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .EntryInfo imageSet = 2;</code>
       */
      public Value.EntryInfo.Builder addImageSetBuilder(
          int index) {
        return getImageSetFieldBuilder().addBuilder(
            index, Value.EntryInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .EntryInfo imageSet = 2;</code>
       */
      public java.util.List<Value.EntryInfo.Builder> 
           getImageSetBuilderList() {
        return getImageSetFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          Value.EntryInfo, Value.EntryInfo.Builder, Value.EntryInfoOrBuilder> 
          getImageSetFieldBuilder() {
        if (imageSetBuilder_ == null) {
          imageSetBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              Value.EntryInfo, Value.EntryInfo.Builder, Value.EntryInfoOrBuilder>(
                  imageSet_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          imageSet_ = null;
        }
        return imageSetBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:ValueInfo)
    }

    static {
      defaultInstance = new ValueInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ValueInfo)
  }

  public interface EntryInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 idImage = 3;
    /**
     * <code>required int64 idImage = 3;</code>
     */
    boolean hasIdImage();
    /**
     * <code>required int64 idImage = 3;</code>
     */
    long getIdImage();

    // required int32 occNumber = 4;
    /**
     * <code>required int32 occNumber = 4;</code>
     */
    boolean hasOccNumber();
    /**
     * <code>required int32 occNumber = 4;</code>
     */
    int getOccNumber();
  }
  /**
   * Protobuf type {@code EntryInfo}
   */
  public static final class EntryInfo extends
      com.google.protobuf.GeneratedMessage
      implements EntryInfoOrBuilder {
    // Use EntryInfo.newBuilder() to construct.
    private EntryInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private EntryInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final EntryInfo defaultInstance;
    public static EntryInfo getDefaultInstance() {
      return defaultInstance;
    }

    public EntryInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private EntryInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 24: {
              bitField0_ |= 0x00000001;
              idImage_ = input.readInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000002;
              occNumber_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Value.internal_static_EntryInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Value.internal_static_EntryInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Value.EntryInfo.class, Value.EntryInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<EntryInfo> PARSER =
        new com.google.protobuf.AbstractParser<EntryInfo>() {
      public EntryInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EntryInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<EntryInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 idImage = 3;
    public static final int IDIMAGE_FIELD_NUMBER = 3;
    private long idImage_;
    /**
     * <code>required int64 idImage = 3;</code>
     */
    public boolean hasIdImage() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 idImage = 3;</code>
     */
    public long getIdImage() {
      return idImage_;
    }

    // required int32 occNumber = 4;
    public static final int OCCNUMBER_FIELD_NUMBER = 4;
    private int occNumber_;
    /**
     * <code>required int32 occNumber = 4;</code>
     */
    public boolean hasOccNumber() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 occNumber = 4;</code>
     */
    public int getOccNumber() {
      return occNumber_;
    }

    private void initFields() {
      idImage_ = 0L;
      occNumber_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasIdImage()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOccNumber()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(3, idImage_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(4, occNumber_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, idImage_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, occNumber_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Value.EntryInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Value.EntryInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Value.EntryInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Value.EntryInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Value.EntryInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Value.EntryInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Value.EntryInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Value.EntryInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Value.EntryInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Value.EntryInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Value.EntryInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code EntryInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Value.EntryInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Value.internal_static_EntryInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Value.internal_static_EntryInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Value.EntryInfo.class, Value.EntryInfo.Builder.class);
      }

      // Construct using Value.EntryInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        idImage_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        occNumber_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Value.internal_static_EntryInfo_descriptor;
      }

      public Value.EntryInfo getDefaultInstanceForType() {
        return Value.EntryInfo.getDefaultInstance();
      }

      public Value.EntryInfo build() {
        Value.EntryInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Value.EntryInfo buildPartial() {
        Value.EntryInfo result = new Value.EntryInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.idImage_ = idImage_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.occNumber_ = occNumber_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Value.EntryInfo) {
          return mergeFrom((Value.EntryInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Value.EntryInfo other) {
        if (other == Value.EntryInfo.getDefaultInstance()) return this;
        if (other.hasIdImage()) {
          setIdImage(other.getIdImage());
        }
        if (other.hasOccNumber()) {
          setOccNumber(other.getOccNumber());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasIdImage()) {
          
          return false;
        }
        if (!hasOccNumber()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Value.EntryInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Value.EntryInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 idImage = 3;
      private long idImage_ ;
      /**
       * <code>required int64 idImage = 3;</code>
       */
      public boolean hasIdImage() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 idImage = 3;</code>
       */
      public long getIdImage() {
        return idImage_;
      }
      /**
       * <code>required int64 idImage = 3;</code>
       */
      public Builder setIdImage(long value) {
        bitField0_ |= 0x00000001;
        idImage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 idImage = 3;</code>
       */
      public Builder clearIdImage() {
        bitField0_ = (bitField0_ & ~0x00000001);
        idImage_ = 0L;
        onChanged();
        return this;
      }

      // required int32 occNumber = 4;
      private int occNumber_ ;
      /**
       * <code>required int32 occNumber = 4;</code>
       */
      public boolean hasOccNumber() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 occNumber = 4;</code>
       */
      public int getOccNumber() {
        return occNumber_;
      }
      /**
       * <code>required int32 occNumber = 4;</code>
       */
      public Builder setOccNumber(int value) {
        bitField0_ |= 0x00000002;
        occNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 occNumber = 4;</code>
       */
      public Builder clearOccNumber() {
        bitField0_ = (bitField0_ & ~0x00000002);
        occNumber_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:EntryInfo)
    }

    static {
      defaultInstance = new EntryInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:EntryInfo)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ValueInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ValueInfo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_EntryInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_EntryInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Value.proto\"6\n\tValueInfo\022\013\n\003nbt\030\001 \002(\003\022" +
      "\034\n\010imageSet\030\002 \003(\0132\n.EntryInfo\"/\n\tEntryIn" +
      "fo\022\017\n\007idImage\030\003 \002(\003\022\021\n\toccNumber\030\004 \002(\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ValueInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ValueInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ValueInfo_descriptor,
              new java.lang.String[] { "Nbt", "ImageSet", });
          internal_static_EntryInfo_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_EntryInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_EntryInfo_descriptor,
              new java.lang.String[] { "IdImage", "OccNumber", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
